### ISSUE TITLE
Extension throws an error upon opening

### ISSUE THREAD

**Issue by JackPieCZ** [jacky917/Rapidgator-DL-Extension#2]
When the icon of the extension is clicked, it throws an error and a message saying _Network response was not ok_ pops up. 
![image](https://github.com/jacky917/Rapidgator-DL-Extension/assets/72486584/a66499e4-c31b-434b-a1de-d82a5d8e838f)

The first error is Error: Failed to fetch thrown by this function at `scripts/content.js:115`:
```javascript
(async function () {
    let premium = document.querySelector('#table_header');
    if (!premium) return;
    try {
        let reliability = await checkReliability();
        updateLoginUI();
        removeUnnecessaryElements();
        renderProgressBar(reliability['data']);
        // 有資料，且高概率是假檔
        if (reliability['data'] === '-1' || reliability['data'] > 50)
            await setupDownloadButton(true);
        else
            await setupDownloadButton(false);
        renderReportButton();
    } catch (error) {
        errorHandler(error);
    }
})();
```

The second error is There has been a problem: Unexpected token '<', "<html> <h"... is not valid JSON thrown by this function at `scripts/popup.js:10`:
```javascript
document.addEventListener('DOMContentLoaded', async function() {
    let p = document.querySelector('#message_p');

    try {
        const domain = await getFromChromeStorage('rg_dl_domain');
        const data = await fetchData(domain + "pub/traffic", { method: 'GET' });

        p.innerHTML = data['data'] === -1 ? "Unlimited" : data['data'] + "%";
    } catch (err) {
        console.error('There has been a problem:', err.message);
    }
});
```

**Comment by jacky917** [comment]
This is because advertising revenue is insufficient to cover the expenses for servers and RG memberships, resulting in a very short period of open access. The service has been temporarily shut down at the moment. If you want to receive news about when the service will be available again promptly, you can join the QQ group, as internal testing within the group will be conducted before any release on GitHub.

**Comment by JackPieCZ** [comment]
How can I join the QQ group?

čt 26. 10. 2023 v 6:04 odesílatel jacky917 ***@***.***>
napsal:
