### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Best2Gamer** [jacky917/Rapidgator-DL-Extension#4]
Hi just discovered this hidden gem and installed it but it doesnt work, it says Network response not ok. pls help...

**Comment by mateus-af** [comment]
ERROR 
Rapidgator-DL-Extension is currently not providing service.

**Comment by foxiergo** [comment]
same

**Comment by jacky917** [comment]
Recently, I've reopened my services, but it's currently available to a limited audience only. If you're interested, please join the QQ group.
