### ISSUE TITLE
啟動錯誤

### ISSUE THREAD

**Issue by liomin** [jacky917/Rapidgator-DL-Extension#5]
<html>
<body>

anonymous) | @ | popup.js:10
-- | -- | --

</body>
</html>

還有這些
ripts/popup.js:10 (匿名函式)
1
2
3
4
5
6
7
8
9
10
11
12
13
document.addEventListener('DOMContentLoaded', async function() {
    let p = document.querySelector('#message_p');

    try {
        const domain = await getFromChromeStorage('rg_dl_domain');
        const data = await fetchData(domain + "pub/traffic", { method: 'GET' });

        p.innerHTML = data['data'] === -1 ? "Unlimited" : data['data'] + "%";
    } catch (err) {
        console.error('There has been a problem:', err.message);
    }
});

那就只有目前這個小問題，啟動不了

**Comment by jacky917** [comment]
近日我重新開放服務了，目前只有小範圍開放，如果需要請加qq群
